version: '3'

services:
  admin:
      container_name: admin
      build:
        context: admin
        dockerfile: Dockerfile
      ports:
        - "80:80"
      networks:
        - microservice

  postgres: 
    container_name: postgres_container
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rootpw}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservice
    # restart: unless-stopped

networks:
    microservice: 
      driver: bridge

volumes:
    postgres: