// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products/product_requests.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe8af1a880a8100, []int{0}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProductRequest)(nil), "pb.CreateProductRequest")
}

func init() {
	proto.RegisterFile("products/product_requests.proto", fileDescriptor_3fe8af1a880a8100)
}

var fileDescriptor_3fe8af1a880a8100 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0x29, 0xd6, 0x87, 0x32, 0xe2, 0x8b, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x8a,
	0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x98, 0x0a, 0x92, 0xa4, 0x30, 0x15, 0xe5, 0xa6, 0x16,
	0x17, 0x27, 0xa6, 0xa7, 0x42, 0x15, 0x29, 0xd9, 0x72, 0x89, 0x38, 0x17, 0xa5, 0x26, 0x96, 0xa4,
	0x06, 0x40, 0xe4, 0x83, 0x20, 0x66, 0x08, 0xa9, 0x72, 0xb1, 0x43, 0x75, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x1b, 0x71, 0xeb, 0x15, 0x24, 0xe9, 0xc1, 0x14, 0xc1, 0xe4, 0x9c, 0x94, 0xa3, 0x14,
	0x13, 0x0b, 0x8b, 0x4a, 0x8b, 0xf5, 0x7d, 0x33, 0x93, 0x8b, 0xf2, 0x8b, 0x53, 0x8b, 0xca, 0x32,
	0x93, 0x53, 0xf5, 0xd3, 0x13, 0x4b, 0x52, 0xcb, 0x13, 0x2b, 0x75, 0x13, 0x0b, 0x32, 0xf5, 0x0b,
	0x92, 0x92, 0xd8, 0xc0, 0x56, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x11, 0x3f, 0xa9, 0x44,
	0xb2, 0x00, 0x00, 0x00,
}
