// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth_responses.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResponse struct {
	Hello                string   `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_686dbbdd1834acb2, []int{0}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
}

func init() {
	proto.RegisterFile("auth/auth_responses.proto", fileDescriptor_686dbbdd1834acb2)
}

var fileDescriptor_686dbbdd1834acb2 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x2c, 0x2d, 0xc9,
	0xd0, 0x07, 0x11, 0xf1, 0x45, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xc5, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0xaa, 0x5c, 0xbc, 0x3e, 0xf9, 0xe9, 0x99, 0x79,
	0x41, 0x50, 0x39, 0x21, 0x11, 0x2e, 0xd6, 0x8c, 0xd4, 0x9c, 0x9c, 0x7c, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x08, 0xc7, 0x49, 0x39, 0x4a, 0x31, 0xb1, 0xb0, 0xa8, 0xb4, 0x58, 0xdf, 0x37,
	0x33, 0xb9, 0x28, 0xbf, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x3f, 0x3d, 0xb1, 0x24, 0xb5,
	0x3c, 0xb1, 0x52, 0x37, 0xb1, 0x20, 0x53, 0xbf, 0x20, 0x29, 0x89, 0x0d, 0x6c, 0xac, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0xdc, 0xb6, 0x5f, 0x73, 0x00, 0x00, 0x00,
}
