// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth_messages.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Login struct {
	Hello                string   `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_479327ae9b66e729, []int{0}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

func init() {
	proto.RegisterType((*Login)(nil), "pb.Login")
}

func init() {
	proto.RegisterFile("auth/auth_messages.proto", fileDescriptor_479327ae9b66e729)
}

var fileDescriptor_479327ae9b66e729 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2c, 0x2d, 0xc9,
	0xd0, 0x07, 0x11, 0xf1, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0xb2, 0x5c, 0xac, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x42,
	0x22, 0x5c, 0xac, 0x19, 0xa9, 0x39, 0x39, 0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x93, 0x72, 0x94, 0x62, 0x62, 0x61, 0x51, 0x69, 0xb1, 0xbe, 0x6f, 0x66, 0x72, 0x51, 0x7e,
	0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x7e, 0x7a, 0x62, 0x49, 0x6a, 0x79, 0x62, 0xa5, 0x6e,
	0x62, 0x41, 0xa6, 0x7e, 0x41, 0x52, 0x12, 0x1b, 0xd8, 0x38, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0x9e, 0xb4, 0xc0, 0x6a, 0x00, 0x00, 0x00,
}
